use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

use crate::model::{EnDeploymentEnvironment, EnVulnerablePackageHistory};

/**
 * Re for request response. En for entity
 */
#[derive(Serialize, Deserialize, FromRow)]
pub struct ReProduct {
    pub id: i32,
    pub title: String,
    pub product_line_id: i16,
    pub packages: Vec<RePackage>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct RePackage {
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub product_id: i32,
    pub versions: Vec<RePackageVersion>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct RePackageVersion {
    pub id: i64,
    pub title: String,
    pub latest_scan: Option<chrono::DateTime<chrono::Utc>>,
    pub package_id: i32,
    pub sbom_id: Option<i64>,
    pub deployment: Option<EnDeploymentEnvironment>,
    pub latest_vulnerable_package_history: Option<EnVulnerablePackageHistory>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct FromQueryReProduct {
    pub p_id: i32,
    pub p_title: String,

    pub pkg_id: Option<i32>,
    pub pkg_title: String,
    pub pkg_description: Option<String>,
    pub pkg_product_id: Option<i16>,

    pub pkgv_id: Option<i32>,
    pub pkgv_title: Option<String>,
    pub pkgv_latest_scan: Option<chrono::DateTime<chrono::Utc>>,
    pub pkgv_sbom_id: Option<i64>,
    pub pkgv_package_id: Option<i32>,

    pub de_id: Option<i16>,
    pub de_internal: Option<bool>,
    pub de_title: Option<String>,

    pub vph_id: Option<i64>,
    pub vph_critical: Option<i16>,
    pub vph_high: Option<i16>,
    pub vpb_medium: Option<i16>,
    pub vph_low: Option<i16>,
    pub vph_info: Option<i16>,
    pub vph_unknown: Option<i16>,
    pub vph_none: Option<i16>,
    pub vph_created_date: Option<chrono::DateTime<chrono::Utc>>,
    pub vph_package_version_id: Option<i64>,
}

/**
 * Test generated by AI. TODO review and test
 */
pub fn map_reproduct(items: Vec<FromQueryReProduct>) -> Vec<ReProduct> {
    let mut products: Vec<ReProduct> = vec![];

    let mut product_map: std::collections::HashMap<i32, ReProduct> =
        std::collections::HashMap::new();

    for res in items {
        if let Some(product) = product_map.get_mut(&res.p_id) {
            if let Some(pkg_id) = res.pkg_id {
                if let Some(pkg) = product.packages.iter_mut().find(|p| p.id == pkg_id) {
                    if let Some(pkgv_id) = res.pkgv_id {
                        let version = RePackageVersion {
                            id: pkgv_id as i64,
                            title: res.pkgv_title.unwrap_or_default(),
                            latest_scan: res.pkgv_latest_scan,
                            package_id: pkg_id,
                            sbom_id: res.pkgv_sbom_id,
                            deployment: res.de_id.map(|_| EnDeploymentEnvironment {
                                id: Some(res.de_id.unwrap_or_default()),
                                internal: res.de_internal.unwrap_or_default(),
                                title: res.de_title.unwrap_or_default(),
                            }),
                            latest_vulnerable_package_history: res.vph_id.map(|_| {
                                EnVulnerablePackageHistory {
                                    id: res.vph_id.unwrap_or_default(),
                                    critical: res.vph_critical.unwrap_or_default(),
                                    high: res.vph_high.unwrap_or_default(),
                                    medium: res.vpb_medium.unwrap_or_default(),
                                    low: res.vph_low.unwrap_or_default(),
                                    info: res.vph_info.unwrap_or_default(),
                                    unknown: res.vph_unknown.unwrap_or_default(),
                                    none: res.vph_none.unwrap_or_default(),
                                    created_date: res.vph_created_date.unwrap_or_default(),
                                    package_version_id: res
                                        .vph_package_version_id
                                        .unwrap_or_default(),
                                }
                            }),
                        };
                        pkg.versions.push(version);
                    }
                } else {
                    let mut versions = vec![];
                    if let Some(pkgv_id) = res.pkgv_id {
                        let version = RePackageVersion {
                            id: pkgv_id as i64,
                            title: res.pkgv_title.unwrap_or_default(),
                            latest_scan: res.pkgv_latest_scan,
                            package_id: pkg_id,
                            sbom_id: res.pkgv_sbom_id,
                            deployment: res.de_id.map(|_| EnDeploymentEnvironment {
                                id: Some(res.de_id.unwrap_or_default()),
                                internal: res.de_internal.unwrap_or_default(),
                                title: res.de_title.unwrap_or_default(),
                            }),
                            latest_vulnerable_package_history: res.vph_id.map(|_| {
                                EnVulnerablePackageHistory {
                                    id: res.vph_id.unwrap_or_default(),
                                    critical: res.vph_critical.unwrap_or_default(),
                                    high: res.vph_high.unwrap_or_default(),
                                    medium: res.vpb_medium.unwrap_or_default(),
                                    low: res.vph_low.unwrap_or_default(),
                                    info: res.vph_info.unwrap_or_default(),
                                    unknown: res.vph_unknown.unwrap_or_default(),
                                    none: res.vph_none.unwrap_or_default(),
                                    created_date: res.vph_created_date.unwrap_or_default(),
                                    package_version_id: res
                                        .vph_package_version_id
                                        .unwrap_or_default(),
                                }
                            }),
                        };
                        versions.push(version);
                    }

                    let package = RePackage {
                        id: pkg_id,
                        title: res.pkg_title.clone(),
                        description: res.pkg_description.clone(),
                        product_id: res.p_id,
                        versions,
                    };
                    product.packages.push(package);
                }
            }
        } else {
            let mut packages = vec![];
            if let Some(pkg_id) = res.pkg_id {
                let mut versions = vec![];
                if let Some(pkgv_id) = res.pkgv_id {
                    let version = RePackageVersion {
                        id: pkgv_id as i64,
                        title: res.pkgv_title.unwrap_or_default(),
                        latest_scan: res.pkgv_latest_scan,
                        package_id: pkg_id,
                        sbom_id: res.pkgv_sbom_id,
                        deployment: res.de_id.map(|_| EnDeploymentEnvironment {
                            id: Some(res.de_id.unwrap_or_default()),
                            internal: res.de_internal.unwrap_or_default(),
                            title: res.de_title.unwrap_or_default(),
                        }),
                        latest_vulnerable_package_history: res.vph_id.map(|_| {
                            EnVulnerablePackageHistory {
                                id: res.vph_id.unwrap_or_default(),
                                critical: res.vph_critical.unwrap_or_default(),
                                high: res.vph_high.unwrap_or_default(),
                                medium: res.vpb_medium.unwrap_or_default(),
                                low: res.vph_low.unwrap_or_default(),
                                info: res.vph_info.unwrap_or_default(),
                                unknown: res.vph_unknown.unwrap_or_default(),
                                none: res.vph_none.unwrap_or_default(),
                                created_date: res.vph_created_date.unwrap_or_default(),
                                package_version_id: res.vph_package_version_id.unwrap_or_default(),
                            }
                        }),
                    };
                    versions.push(version);
                }

                let package = RePackage {
                    id: pkg_id,
                    title: res.pkg_title.clone(),
                    description: res.pkg_description.clone(),
                    product_id: res.p_id,
                    versions,
                };
                packages.push(package);
            }

            let product = ReProduct {
                id: res.p_id,
                title: res.p_title.clone(),
                product_line_id: res.pkg_product_id.unwrap_or_default() as i16,
                packages,
            };
            product_map.insert(res.p_id, product);
        }
    }
    /*
    match product_lines.iter_mut().find(|pl| pl.id == res.pl_id) {
        Some(_product_line) => {}
        None => {
            let product_line: EnProductLineProducts = EnProductLineProducts {
                id: res.pl_id,
                title: res.pl_title,
                //owners: res.pl_owners,
                products: vec![],
            };
            product_lines.push(product_line);
        }
    };

    if let Some(p_id) = res.p_id {
        if let Some(p_title) = res.p_title {
            if let Some(p_product_line_id) = res.p_product_line_id {
                if let Some(product_line) =
                    product_lines.iter_mut().find(|pl| pl.id == res.pl_id)
                {
                    product_line.products.push(EnProduct {
                        id: p_id,
                        title: p_title,
                        product_line_id: p_product_line_id,
                    });
                };
            };
        };
    };
     */

    products.sort_by(|a, b| a.title.cmp(&b.title));
    products
}
