use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

use crate::model::{EnDeploymentEnvironment, EnVulnerablePackageHistory};

/**
 * Re for request response. En for entity
 */
#[derive(Serialize, Deserialize, FromRow)]
pub struct ReProduct {
    pub id: i32,
    pub title: String,
    pub product_line_id: i16,
    pub packages: Vec<RePackage>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct RePackage {
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub product_id: i32,
    pub versions: Vec<RePackageVersion>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct RePackageVersion {
    pub id: i64,
    pub title: String,
    pub latest_scan: Option<chrono::DateTime<chrono::Utc>>,
    pub package_id: i32,
    pub sbom_id: Option<i64>,
    pub deployment: Option<EnDeploymentEnvironment>,
    pub latest_vulnerable_package_history: Option<EnVulnerablePackageHistory>,
}

#[derive(Serialize, Deserialize, FromRow)]
pub struct FromQueryReProduct {
    pub p_id: i32,
    pub p_title: String,
    pub p_product_line_id: i16,

    pub pkg_id: Option<i32>,
    pub pkg_title: String,
    pub pkg_description: Option<String>,
    pub pkg_product_id: Option<i32>,

    pub pkgv_id: Option<i64>,
    pub pkgv_title: Option<String>,
    pub pkgv_latest_scan: Option<chrono::DateTime<chrono::Utc>>,
    pub pkgv_sbom_id: Option<i64>,
    pub pkgv_package_id: Option<i32>,

    pub de_id: Option<i16>,
    pub de_internal: Option<bool>,
    pub de_title: Option<String>,

    pub vph_id: Option<i64>,
    pub vph_critical: Option<i16>,
    pub vph_high: Option<i16>,
    pub vpb_medium: Option<i16>,
    pub vph_low: Option<i16>,
    pub vph_info: Option<i16>,
    pub vph_unknown: Option<i16>,
    pub vph_none: Option<i16>,
    pub vph_created_date: Option<chrono::DateTime<chrono::Utc>>,
    pub vph_package_version_id: Option<i64>,
}

/**
 * Code generated by AI. TODO clean the unwrap.
 */
pub fn map_reproduct(items: Vec<FromQueryReProduct>) -> Option<ReProduct> {
    let mut product: Option<ReProduct> = None;

    for item in items {
        if product.is_none() {
            product = Some(ReProduct {
                id: item.p_id,
                title: item.p_title.clone(),
                product_line_id: item.p_product_line_id,
                packages: Vec::new(),
            });
        }

        let product = product.as_mut().unwrap();

        if let Some(pkg_id) = item.pkg_id {
            let package = match product.packages.iter_mut().find(|p| p.id == pkg_id) {
                Some(package) => package,
                None => {
                    let new_package = RePackage {
                        id: pkg_id,
                        title: item.pkg_title.clone(),
                        description: item.pkg_description.clone(),
                        product_id: item.pkg_product_id.unwrap_or(item.p_id as i32),
                        versions: Vec::new(),
                    };
                    product.packages.push(new_package);
                    product.packages.last_mut().unwrap()
                }
            };

            if let Some(pkgv_id) = item.pkgv_id {
                let version = match package.versions.iter_mut().find(|v| v.id == pkgv_id) {
                    Some(version) => version,
                    None => {
                        let new_version = RePackageVersion {
                            id: pkgv_id,
                            title: item.pkgv_title.clone().unwrap_or_default(),
                            latest_scan: item.pkgv_latest_scan,
                            package_id: item.pkgv_package_id.unwrap_or(pkg_id),
                            sbom_id: item.pkgv_sbom_id,
                            deployment: item.de_id.map(|_| EnDeploymentEnvironment {
                                id: item.de_id,
                                internal: item.de_internal.unwrap_or(false),
                                title: item.de_title.clone().unwrap_or_default(),
                            }),
                            latest_vulnerable_package_history: item.vph_id.map(|_| {
                                EnVulnerablePackageHistory {
                                    id: item.vph_id.unwrap_or(0),
                                    critical: item.vph_critical.unwrap_or(0),
                                    high: item.vph_high.unwrap_or(0),
                                    medium: item.vpb_medium.unwrap_or(0),
                                    low: item.vph_low.unwrap_or(0),
                                    info: item.vph_info.unwrap_or(0),
                                    unknown: item.vph_unknown.unwrap_or(0),
                                    none: item.vph_none.unwrap_or(0),
                                    created_date: item.vph_created_date.unwrap_or(Utc::now()),
                                    package_version_id: item.vph_package_version_id.unwrap_or(0),
                                }
                            }),
                        };
                        package.versions.push(new_version);
                        package.versions.last_mut().unwrap()
                    }
                };
            }
        }
    }
    /*
    let mut products = Vec::new();
    if let Some(p) = product {
        products.push(p);
    }
    products.sort_by(|a, b| a.title.cmp(&b.title));
    let mut products: Vec<ReProduct> = vec![];

    for item in items {
        let product = match products.iter_mut().find(|p| p.id == item.p_id) {
            Some(product) => product,
            None => {
                let new_product = ReProduct {
                    id: item.p_id,
                    title: item.p_title.clone(),
                    product_line_id: item.p_product_line_id,
                    packages: Vec::new(),
                };
                products.push(new_product);
                products.last_mut().unwrap()
            }
        };

        if let Some(pkg_id) = item.pkg_id {
            let package = match product.packages.iter_mut().find(|p| p.id == pkg_id) {
                Some(package) => package,
                None => {
                    let new_package = RePackage {
                        id: pkg_id,
                        title: item.pkg_title.clone(),
                        description: item.pkg_description.clone(),
                        product_id: item.pkg_product_id.unwrap_or(item.p_id as i32),
                        versions: Vec::new(),
                    };
                    product.packages.push(new_package);
                    product.packages.last_mut().unwrap()
                }
            };

            if let Some(pkgv_id) = item.pkgv_id {
                let version = match package.versions.iter_mut().find(|v| v.id == pkgv_id) {
                    Some(version) => version,
                    None => {
                        let new_version = RePackageVersion {
                            id: pkgv_id,
                            title: item.pkgv_title.clone().unwrap_or_default(),
                            latest_scan: item.pkgv_latest_scan,
                            package_id: item.pkgv_package_id.unwrap_or(pkg_id),
                            sbom_id: item.pkgv_sbom_id,
                            deployment: item.de_id.map(|_| EnDeploymentEnvironment {
                                id: item.de_id,
                                internal: item.de_internal.unwrap_or(false),
                                title: item.de_title.clone().unwrap_or_default(),
                            }),
                            latest_vulnerable_package_history: item.vph_id.map(|_| {
                                EnVulnerablePackageHistory {
                                    id: item.vph_id.unwrap_or(0),
                                    critical: item.vph_critical.unwrap_or(0),
                                    high: item.vph_high.unwrap_or(0),
                                    medium: item.vpb_medium.unwrap_or(0),
                                    low: item.vph_low.unwrap_or(0),
                                    info: item.vph_info.unwrap_or(0),
                                    unknown: item.vph_unknown.unwrap_or(0),
                                    none: item.vph_none.unwrap_or(0),
                                    created_date: item.vph_created_date.unwrap_or(Utc::now()),
                                    package_version_id: item.vph_package_version_id.unwrap_or(0),
                                }
                            }),
                        };
                        package.versions.push(new_version);
                        package.versions.last_mut().unwrap()
                    }
                };
            }
        }
    }

    products.sort_by(|a, b| a.title.cmp(&b.title));
     */
    product
}
